### ISSUE TITLE
Corrupted data on write, results in `dist overflow` error on read.

### ISSUE THREAD

**Issue by nlfiedler** [dyz1990/sevenz-rust#12]
Encountered an issue when writing binary files to a compressed archive. Didn't notice it with the text files I was using during testing. Not sure if it's certain kinds of binary files or something else, but `sevenz-rust` produces corrupted files that 7-zip cannot read. Attempting to decompress these files with `sevenz-rust` results in a `dist overflow` error. Since the reproduction involves a 1mb file, I've created a repository with the example code and PDF file.

https://github.com/nlfiedler/sevenz-overflow

I'm using `rustc` 1.67 and the latest `sevenz-rust` crate. I'm hoping I'm just doing it wrong and you will point out my error. Thank you.

**Comment by dyz1990** [comment]
@nlfiedler You are right. There are bugs in the lzma encoder. I'll fix these bugs and release 0.2.5

**Comment by dyz1990** [comment]
@nlfiedler this issues is fixed in version 0.2.6,with sub crate lzma-rust 0.1.1.
Thanks for reporting this issue.

**Comment by nlfiedler** [comment]
I've verified with my test and it works. Thank you.
