### ISSUE TITLE
Solid compression not working with version 0.3

### ISSUE THREAD

**Issue by JoachimBe** [dyz1990/sevenz-rust#24]
Hi, 
the solid compression is not working when you use version 0.3 in the Cargo.toml
![push_not_working_in_03](https://github.com/dyz1990/sevenz-rust/assets/15607143/98145334-bf9e-4a4c-a9f5-3187bf05f424)

I change to version 0.4 and it seems to work. 

Just in case someone is facing the same issue.

**Comment by dyz1990** [comment]
@JoachimBe  Thank you for your report. The version code used by the solid compression example in the README.md has been updated to 0.4.
