### ISSUE TITLE
Is it possible to track decompression progress?

### ISSUE THREAD

**Issue by T3kla** [dyz1990/sevenz-rust#25]
Hello!

Firs of all, this crate is awesome and you made my work so much easier.

That said, I'm doing an installer that needs to display a progress bar with the download and decompression progress.

As the example show, I now have this function:
```rust
    let res = decompress_with_extract_fn_and_password(
        file,
        dst,
        "mypass".into(),
        |entry, reader, dest| {
            println!("start extract {}", entry.name());
            let r = default_entry_extract_fn(entry, reader, dest);
            println!("complete extract {}", entry.name());
            r
        },
    );
```

Is there a way to get the progress?

**Comment by dyz1990** [comment]
@T3kla I added an example that can show the progress of decompression

**Comment by T3kla** [comment]
That is awesome! Thank you!
