### ISSUE TITLE
Multi input/output stream coders are not yet supported

### ISSUE THREAD

**Issue by bonigarcia** [dyz1990/sevenz-rust#32]
I got the error `Multi input/output stream coders are not yet supported` when calling to `sevenz_rust::decompress_file` of an 7z file. It seems it is a limitation in the current implementation. 

Is there any plan to support it?

Thank you very much.

**Comment by dyz1990** [comment]
Yes, check this issue #28

**Comment by bonigarcia** [comment]
Thank you, @dyz1990. I'm closing this issue, and will check it from there.
