### ISSUE TITLE
Bug: Unable to decompress due to bad signature error.

### ISSUE THREAD

**Issue by basicfunc** [dyz1990/sevenz-rust#33]
Hi there, I was trying to decompress vscode archive, using this library it fails due to bad signature error, however through cli, I'm able to decompresses it successfully, below are screenshots for same.

Using Rust code:
```rust
pub fn install(app: &str) {
    let query = app.trim().to_lowercase();

    let (app_name, manifest) = match query.split_once('/') {
        Some((bucket, app_name)) => (
            app_name,
            Buckets::query_app(app_name)
                .unwrap()
                .get_app_from(app_name, bucket),
        ),
        None => (app, Buckets::query_app(app).unwrap().get_app(app)),
    };

    let manifest = manifest.unwrap();
    let file_name = Downloader::download(app_name, true).unwrap();
    let cache_dir = Config::cache_dir().unwrap();

    let srcs = file_name
        .iter()
        .map(|f| match f {
            DownloadStatus::Downloaded(s) => s,
            DownloadStatus::DownloadedAndVerified(s) => s,
            DownloadStatus::AlreadyInCache(s) => s,
        })
        .map(|s| cache_dir.join(s))
        .collect::<Vec<_>>();

    let version = &manifest.version;

    let app_dir = Config::app_dir().unwrap();
    let app_dir = app_dir.join(app_name);
    let app_dir = app_dir.join(version);

    if !app_dir.exists() {
        PathBuf::create(app_dir.clone()).unwrap();
        use sevenz_rust::decompress_file;
        for src in srcs {
            if src
                .extension()
                .unwrap_or_default()
                .to_string_lossy()
                .to_string()
                == "7z"
            {
                println!("decompressingn {:?}", src);
                decompress_file(src, &app_dir).unwrap();
            }
        }
    }

    // println!("{app_name}\n{manifest:#?}\n{file_name:#?} at {app_dir:?}");
}
```
I gets:
![image](https://github.com/dyz1990/sevenz-rust/assets/84739019/b7b55ae2-35cb-45fe-82db-bb27ec02f91b)

However using `7z` cli:
![image](https://github.com/dyz1990/sevenz-rust/assets/84739019/1ea0849c-daed-4522-8a5b-e06276138724)

**Comment by dyz1990** [comment]
it is not a '7z' archive, but a 'zip' archive.
you can see the warning  of the  7z cli.

**Comment by basicfunc** [comment]
> it is not a '7z' archive, but a 'zip' archive. you can see the warning of the 7z cli.

Isn't it supposed to handle zip file as well, as 7z does?

**Comment by dyz1990** [comment]
> > it is not a '7z' archive, but a 'zip' archive. you can see the warning of the 7z cli.
> 
> Isn't it supposed to handle zip file as well, as 7z does?
No, This library is not like the 7z cli program, it is only used to compress and decompress files in 7z format. 
And there are certain features in 7z this lib doesn't support,

**Comment by basicfunc** [comment]
Okay thanks!!
