### ISSUE TITLE
Compressed folder missing directory structure

### ISSUE THREAD

**Issue by AlanWeekend** [dyz1990/sevenz-rust#35]
this is my dir
![image](https://github.com/dyz1990/sevenz-rust/assets/24834613/9275730c-a37e-479e-813e-a1cc80354cbd)

this is output.7z
![image](https://github.com/dyz1990/sevenz-rust/assets/24834613/bbb03220-a471-4f1a-a3a0-82331afe1676)

this is my code
```
fn main() {
    sevenz_rust::compress_to_path_encrypted(
        r"E:\work\cocos\output",
        r"E:\work\cocos\output.7z",
        "a19970411".into(),
    )
    .expect("compress ok");
    println!("Hello, world!");
}

```

it runs on windows system

**Comment by dyz1990** [comment]
@AlanWeekend I don't know how BandZip reads the directory structure. Does version 0.5.1 fix this issue?

**Comment by dyz1990** [comment]
I replaced the file separator from "\" to "/" and it looks OK

**Comment by AlanWeekend** [comment]
![image](https://github.com/dyz1990/sevenz-rust/assets/24834613/ced7a8ef-1cf4-4652-ae49-2812f90d5320)

this is using 0.5.1 version ，It can already create folders, but the directory structure is still incorrect。Additionally, I have discovered version 0.5.2 on Crates, but I am currently unable to use it. It is estimated that the cache has not been updated yet. I will try using version 0.5.2 later and submit a new report

**Comment by AlanWeekend** [comment]
![image](https://github.com/dyz1990/sevenz-rust/assets/24834613/ce875eba-fa4c-4c36-b261-553fe8186ea9)

0.5.2 is correct, thank you for your help
