### ISSUE TITLE
UnsupportedCompressionMethod("AES256SHA256")

### ISSUE THREAD

**Issue by zy97** [dyz1990/sevenz-rust#4]
Unencrypted 7z files can be decompressed, but 7z files encrypted with 7z software will panic, prompting UnsupportedCompressionMethod("AES256SHA256")

**Comment by dyz1990** [comment]
> Unencrypted 7z files can be decompressed, but 7z files encrypted with 7z software will panic, prompting UnsupportedCompressionMethod("AES256SHA256")

安排

**Comment by zy97** [comment]
> > Unencrypted 7z files can be decompressed, but 7z files encrypted with 7z software will panic, prompting UnsupportedCompressionMethod("AES256SHA256")
> 
> 安排
看到中文瞬间就亲切了

**Comment by dyz1990** [comment]
@zy97 0.1.5 增加AES256SHA256 支持，可以解压加密的7z文件


Decompress a encrypted 7z file

Add 'aes256' feature
```
[dependencies]
sevenz-rust={version="0.1.5", features=["aes256"]}
```

```
sevenz_rust::decompress_file_with_password("path/to/encrypted.7z", "path/to/output", "password".into()).expect("complete");

```
