### ISSUE TITLE
Encrypt file names, hide the directory structure

### ISSUE THREAD

**Issue by VictorieeMan** [dyz1990/sevenz-rust#55]
Is there a way to encrypt the header so that the file structure is hidden? The 7z GUI provides this option for  this called "Encrypt file names" but more precisely it's about encrypting the header of the archive. On the cli one can do this: `-mhe=on`
```
7z a -p -mhe=on archive.7z file_to_compress
```
ref. [using-7z-command-line-with-aes-256](https://devicetests.com/using-7z-command-line-with-aes-256-encryption-and-encrypting-filenames)

**Comment by VictorieeMan** [comment]
nice :)

**Comment by rubenh2905** [comment]
it's not doing it because
![image](https://github.com/user-attachments/assets/8e6bd9fa-99bc-4d01-9b84-1b4f0ff5b1a6)
compression made it worse my ass, make an extera function to force it to encrypt/hide file names by force IDC
